name: example
description: Cornerstone implementation in a pure dart app

publish_to: "none"

version: 2.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  cornerstone:
    path: ../
  dartz: ^0.10.0-nullsafety.1
  dio: ^4.0.0-beta4
  equatable: ^2.0.0
  json_annotation: ^4.0.0
  get_it: ^6.0.0
  hive: ^1.6.0-nullsafety.2
  intl: ^0.17.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: "^1.11.5"
  coverage: ^1.0.1
  json_serializable: ^4.0.2
  mockito: ^5.0.0
  test: ^1.14.6
