name: cornerstone
description: A library written in pure dart to help devs set up dart projects with a proper architecture without having to write a lot of boilerplate code. Inspired by clean architecture.
version: 2.0.0-nullsafety.11
repository: https://www.github.com/moseskarunia/cornerstone

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  clock: ^1.1.0
  dartz: ^0.10.0-nullsafety.1
  equatable: ^2.0.0
  hive: ^2.0.0
  json_annotation: ^4.0.0
  meta: ^1.3.0

dev_dependencies:
  build_runner: ^1.11.5  
  coverage: ^1.0.1
  mocktail: ^0.1.4
  test: ^1.16.5
